# Generated by Django 2.1.5 on 2019-05-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/board_img/')),
            ],
        ),
        migrations.CreateModel(
            name='DonationOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='기부단체명')),
                ('desc', models.TextField(verbose_name='단체설명')),
                ('photo', models.ImageField(upload_to='staff/donation/')),
                ('url', models.URLField(max_length=250, verbose_name='홈페이지 주소')),
            ],
        ),
    ]
