# Generated by Django 2.1.5 on 2019-05-15 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(599)], verbose_name='경험치')),
                ('weed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='잡초개수')),
                ('harvest', models.DateField(blank=True, null=True, verbose_name='수확날짜')),
            ],
            options={
                'verbose_name': '작물',
                'verbose_name_plural': '작물일지',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='씨앗종류')),
                ('photo', models.ImageField(upload_to='seed/', verbose_name='사진')),
                ('desc', models.TextField(max_length=50, verbose_name='씨앗정보')),
            ],
            options={
                'verbose_name': '씨앗',
                'verbose_name_plural': '씨앗정보',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10, verbose_name='상태')),
            ],
            options={
                'verbose_name': '작물상태',
                'verbose_name_plural': '작물상태',
            },
        ),
    ]
