# Generated by Django 2.1.5 on 2019-05-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.DonationOrg', verbose_name='작물상태'),
        ),
        migrations.AddField(
            model_name='diary',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Seed', verbose_name='씨앗종류'),
        ),
        migrations.AddField(
            model_name='diary',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.State', verbose_name='작물상태'),
        ),
    ]
